### ISSUE TITLE
password resetting without email confirmation

### ISSUE THREAD

**Issue by kieranwild** [riverrun/openmaize-phoenix-example#10]
Hi,
Is there an easy way to have password resetting without having email confirmation?
Cheers
Kieran

**Comment by riverrun** [comment]
Yes, that's on the `basic` branch. I'll update the README later to make that clearer.

To get the app that is on the `basic` branch, starting from scratch:

1. run `mix phoenix.new` (with the name of your app)
2. configure your database
3. add openmaize to your mix.exs file
4. run `mix openmaize.gen.phoenixauth`

Further details are in [this guide](https://github.com/riverrun/openmaize/blob/master/phoenix_new_openmaize.md).

**Comment by riverrun** [comment]
Updated README
