### ISSUE TITLE
Add unprotected routes to the example

### ISSUE THREAD

**Issue by Pjino** [riverrun/openmaize-phoenix-example#12]
As I use protected and unprotected routes in the same app it could be simple to add in the router.ex a new pipeline/scope that make explicit how to do that.
Thanks!

**Comment by riverrun** [comment]
I think I'll add this to the Openmaize wiki. I'll let you know when that's done.

**Comment by Pjino** [comment]
Thank you.

**Comment by riverrun** [comment]
Updated -- eventually :)

**Comment by Pjino** [comment]
Great!
Thank you.
