### ISSUE TITLE
Password reset link in email does not work

### ISSUE THREAD

**Issue by fabrik42** [riverrun/openmaize-phoenix-example#14]
The link generated in the [password reset email](https://github.com/riverrun/openmaize-phoenix-example/blob/master/lib/email.ex#L35) does not match any of the [generated routes](https://github.com/riverrun/openmaize-phoenix-example/blob/master/web/router.ex#L21), because the `:id` part is missing in `/password_resets/:id/edit`.

There are a couple of solutions for this problem:
* Use the path helper in emails and set the email as the id - this would need the PasswordResetController to change
* Use a dummy id in the route like `/password_resets/by_mail/edit`
* Take the edit part out of the resources and write it explicitly like this:

```elixir
resources "/password_resets", PasswordResetController, only: [:new, :create, :update]
get "/password_resets/edit", PasswordResetController, :edit
```

This would make the `password_reset_path(:edit)` work out like in the mailer: `"/password_resets/edit"`. I think this would be the cleanest approach.

I would be happy to create a pull request, I just wanted to get your opinion first, how to tackle this problem.

**Comment by riverrun** [comment]
I'll look into this over the weekend.

**Comment by fabrik42** [comment]
Thank you! Let me know if I can be of any help.

**Comment by riverrun** [comment]
I've just updated the installer with fixes for this problem.

I decided to follow your suggestion of pulling the `edit` out of the resources line, and I also removed `update` as well. I think there's no real need for an id in the update route.

**Comment by fabrik42** [comment]
Awesome! Thanks!
